name: 'Add Issue to Project vNext'
description: 'Adds an issue to a Project vNext board'
author: 'cmbrose'
inputs:
  issue-id:
    required: true
    description: 'The id number of the issue to add'
  project-next-id:
    required: true
    description: 'The id number of the Project to update'
  organization:
    required: true
    description: 'The organization name the Project belongs to'
runs:
  using: 'node12'
  main: 'dist/index.js'
